name: flake8 Lint

env:
  pylint_v: 2.17.0
  pylint_exit_ver: 1.2.0
  flake8_v: 6.0.0

on:
  push:
    branches-ignore:
      - main

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Create virtual environment
        run: python -m venv venv
        working-directory: ${{ github.workspace }}
      
      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          deactivate
        working-directory: ${{ github.workspace }}
      
      - name: Analyze code with Pylint
        run: |
          source venv/bin/activate
          pylint $(git ls-files '*.py')
          deactivate
        working-directory: ${{ github.workspace }}