name: Pylint

env:
  pylint_v: 2.17.0
  pylint_exit_ver: 1.2.0
  flake8_v: 6.0.0


on:
  push:
    branches-ignore:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==$pylint_v pylint-exit==$pylint_exit_ver flake8==$flake8_v

    - name: Get list of changed Python files
      id: changed_files
      run: |
        # Fetch the base branch so we can compare changes
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
        # Get the list of changed files
        tmp_files=$(git diff --diff-filter=ACM --name-only ${{ github.base_ref }})
        echo "Changed files are $tmp_files"
        # Filter only Python files
        tmp_pfiles=$(echo "$tmp_files" | grep "\.py$" || true)
        echo "Python files are $tmp_pfiles"
        echo "::set-output name=python_files::$tmp_pfiles"

    - name: Run flake8 on modified Python files
      if: steps.changed_files.outputs.python_files != ''
      run: |
        flake8 --ignore=W --exclude=__init__.py,queries.py,venv --statistics --count --max-line-length=90 ${{ steps.changed_files.outputs.python_files }}

    - name: Run pylint on modified Python files
      if: steps.changed_files.outputs.python_files != ''
      run: |
        pylint -ry --disable=E0401,E0611,R0903,R0913,W --output-format=text ${{ steps.changed_files.outputs.python_files }} | tee /tmp/pylint.txt || pylint-exit --error-fail --refactor-fail --convention-fail $?
