name: flake8 Lint

on:
  push:
    branches-ignore:
      - main

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Create virtual environment
        run: python -m venv venv
        working-directory: ${{ github.workspace }}
      
      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          deactivate
        working-directory: ${{ github.workspace }}
      
      - name: Analyze code with flake8
        run: |
          source venv/bin/activate
          flake8 --ignore=W --exclude=__init__.py, queries.py, venv, env --statistics --count --max-line-length=90
          deactivate
        working-directory: ${{ github.workspace }}

      - name: Analyze code with Pylint
        run: |
          source venv/bin/activate
          pylint -ry --disable=E0401,E0611,R0903,R0913 --output-format=text *.py
          deactivate
        working-directory: ${{ github.workspace }}