name: flake8 Lint

env:
  pylint_v: 2.17.0
  pylint_exit_ver: 1.2.0
  flake8_v: 6.0.0

on:
  push:
    branches-ignore:
      - main

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E0401,E0611,R0903,R0913"
          exclude: "__init__.py, queries.py, venv"
          max-line-length: "90"
          path: "/"